### ISSUE TITLE
I don't know how to test your code? So many bugs, are you seriously?

### ISSUE THREAD

**Issue by zwyking** [wookiekim/transformatcher#1]
Watch your dataset.py, where is the `self.src_bbox' from? I really doubt your reality of your paper?

**Comment by wookiekim** [comment]
Hello @zwyking , sorry for your frustration.
I assume that particular error occurs when testing for PF-WILLOW, while it worked fine for PF-PASCAL or SPair-71k datasets.
While TransforMatcher does not need the bounding boxes for training or testing, the current dataset code contains traces of my previous experiments / endeavors.

The most recent commit (https://github.com/wookiekim/transformatcher/commit/f4c134fc6cb1cfad716fc4cfddb5e0ba8f085bcc) has fixed that error by simply ruling out that part when testing for PF-WILLOW. This is just a makeshift, and I will update the code to remove all unnecessary part for better usability.
(Note that the same was done for the results reported in the paper.)

Please do tell us if you are facing other bugs as well.
Thanks,
Seungwook

**Comment by zwyking** [comment]
Hi, thanks for your reply. I have followed your advice to run the test codes and it works! However, the results I got takes a marginal performance gap with your reported results. I am sure training the model with the default setting that provided in your project. Could you know why it? If necessary, I could provide my results to you. Or, you can provide your model to me? 

Thanks.

**Comment by wookiekim** [comment]
Hello @zwyking, sorry for the late reply.
It would be much more beneficial to train the model for longer epochs (~50 epochs) by setting --niter to a higher number.
For the results reported in the paper, the code was trained for around 70 epochs.
I will update the basic configurations, and upload the pretrained weights ASAP.
In the meanwhile, I am sure using higher number of iterations will improve your performance.

Best, 
Seungwook
