### ISSUE TITLE
question on table 1

### ISSUE THREAD

**Issue by Tsingularity** [wookiekim/transformatcher#3]
Hi, thanks for the great work!

Just wondering what's the difference between 0.1(F) and 0.1(T) in table 1? It seems that it leads to a huge difference on final PCK number.

Thanks!

**Comment by Tsingularity** [comment]
also wondering what's the difference between alpha_bbox and alpha_bbox-kp?

**Comment by wookiekim** [comment]
Hello, I apologize for the delayed reply.

In Table 1, the difference between 0.1(F) and 0.1(T) is the dataset which the model was trained on.
F - which refers to "F"inetune - means that the model was trained on the same dataset it is being evaluated on.
T - which refers to "T"ransfer - means that the model was trained on PF-PASCAL, to be evaluated on another dataset.

The difference between alpha_bbox and alpha_bbox-kp is:
bbox uses a bounding box that loosely covers the object as it uses a single keypoint position, typically yielding better PCK results.
bbox-kp uses two keypoint positions to approximate a bounding box that tightly wraps the target object.
Existing work have mainly used either one of these two schemes, and we provided the results for both schemes to facilitate future work.

Thank you for your interest in our work!
