### ISSUE TITLE
is bounding box crop used in evaluation?

### ISSUE THREAD

**Issue by Tsingularity** [wookiekim/transformatcher#4]
Hi, thanks for the great work!

I'm just wondering, when evaluating the PCK, is the original image used as input to the model? Or the bounding-box cropped image used as input?

Thanks!

**Comment by wookiekim** [comment]
Hello, thank you for this question!

When evaluating the PCK, the original image is used as the input, NOT the bounding-box cropped input.

Hope this helps!
